In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
import seaborn as sns

# Load Iris Dataset

iris = datasets.load_iris()
X=iris.data 
y=iris.target

# Split into Training and Testing 

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state= 42,stratify=y)

# Standardize 

scaler = StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

# Train Model and make Predictions

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [3]:
# Evaluate the Model

accuracy= accuracy_score(y_test,y_pred)
print(f'accuracy: {accuracy:2f}')
print("\nclassification report :")
print(classification_report(y_test,y_pred))
c=confusion_matrix(y_test,y_pred)
print('Confusion Matrix:')
print(c)

accuracy: 0.933333

classification report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]
